package com.mercan.fuzulplanim.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.mercan.fuzulplanim.MainViewModel
import com.mercan.fuzulplanim.data.*
import com.mercan.fuzulplanim.util.*
import java.time.LocalDate
import java.time.YearMonth

@Composable
fun FixedExpensesScreen(vm:MainViewModel,fixed:List<FixedExpenseEntity>){var edit by remember{mutableStateOf<FixedExpenseEntity?>(null)};var add by remember{mutableStateOf(false)};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{SectionTitle("Sabit Giderler","Yeni gider eklediğinde aylık planına fark olarak yansır"){FilledTonalButton(onClick={add=true}){Icon(Icons.Rounded.Add,null);Text(" Ekle")}}};item{AppCard{KeyValue("Aktif aylık toplam",tl(fixed.filter{it.active}.sumOf{it.amount}));Text("Excel'den gelen giderlerde baseline korunur; değişiklik yalnız fark olarak projeksiyona eklenir.",fontSize=11.sp,color=Muted,modifier=Modifier.padding(top=8.dp))}};if(fixed.isEmpty())item{EmptyState("Sabit gider yok","Yeni sabit gider ekleyebilir veya Excel'den aktarabilirsin.","Yeni gider ekle"){add=true}};items(fixed,key={it.id}){f->AppCard(onClick={edit=f}){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(f.name,fontWeight=FontWeight.SemiBold);Text("${f.category} • ${f.paymentSource.ifBlank{"Kaynak belirtilmedi"}}",color=Muted,fontSize=12.sp,modifier=Modifier.padding(top=3.dp));Row(Modifier.padding(top=6.dp),horizontalArrangement=Arrangement.spacedBy(6.dp)){if(f.imported)Pill("Excel",Blue);if(f.inflationLinked)Pill("Enflasyon",Amber);if(!f.active)Pill("Pasif",Red)}};Text(tl(f.amount),fontWeight=FontWeight.Bold,color=if(f.active)Ink else Muted)}}}};if(add)FixedDialog(null,vm){add=false};edit?.let{FixedDialog(it,vm){edit=null}}}

@Composable private fun FixedDialog(item:FixedExpenseEntity?,vm:MainViewModel,onDismiss:()->Unit){var name by remember{mutableStateOf(item?.name.orEmpty())};var cat by remember{mutableStateOf(item?.category?:"Fatura")};var amount by remember{mutableStateOf(item?.amount?.toString()?:"")};var source by remember{mutableStateOf(item?.paymentSource.orEmpty())};var group by remember{mutableStateOf(item?.budgetGroup?:"bills")};var start by remember{mutableStateOf(item?.startMonth?.ifBlank{YearMonth.now().toString()}?:YearMonth.now().toString())};var day by remember{mutableStateOf((item?.dayOfMonth?:1).toString())};var inflation by remember{mutableStateOf(item?.inflationLinked?:false)};var annual by remember{mutableStateOf((item?.annualInflationPct?:0.0).toString())};var active by remember{mutableStateOf(item?.active?:true)};AlertDialog(onDismissRequest=onDismiss,title={Text(if(item==null)"Yeni sabit gider" else "Sabit gideri düzenle")},text={LazyColumn(Modifier.heightIn(max=500.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){item{FormField("Ad",name,{name=it})};item{FormField("Kategori",cat,{cat=it})};item{FormField("Aylık tutar",amount,{amount=it},true)};item{FormField("Ödeme / kaynak",source,{source=it})};item{FormField("Bütçe grubu: bills/living/education/transport/other",group,{group=it})};item{FormField("Başlangıç ayı YYYY-MM",start,{start=it})};item{FormField("Ödeme günü 1-28",day,{day=it},true)};item{Row(verticalAlignment=Alignment.CenterVertically){Checkbox(inflation,{inflation=it});Text("Enflasyona bağlı")}};if(inflation)item{FormField("Yıllık oran %",annual,{annual=it},true)};if(item!=null)item{Row(verticalAlignment=Alignment.CenterVertically){Checkbox(active,{active=it});Text("Aktif")}}}},confirmButton={TextButton(onClick={val x=if(item==null)vm.newFixed(name,cat,doubleInput(amount),source,group,start,day.toIntOrNull()?:1,inflation,doubleInput(annual))else item.copy(name=name,category=cat,amount=doubleInput(amount),paymentSource=source,budgetGroup=group,startMonth=start,dayOfMonth=(day.toIntOrNull()?:1).coerceIn(1,28),inflationLinked=inflation,annualInflationPct=doubleInput(annual),active=active);vm.saveFixed(x);onDismiss()}){Text("Kaydet")}},dismissButton={Row{if(item!=null)TextButton(onClick={vm.deleteFixed(item);onDismiss()}){Text("Sil",color=Red)};TextButton(onClick=onDismiss){Text("Vazgeç")}}})}

@Composable
fun CardsScreen(vm:MainViewModel,cards:List<CardEntity>,installments:List<InstallmentEntity>){var addCard by remember{mutableStateOf(false)};var addInst by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<InstallmentEntity?>(null)};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{SectionTitle("Kartlar & Taksitler","Güncel ekstre, kalan borç ve gelecek aylık yük")};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick={addCard=true},modifier=Modifier.weight(1f)){Icon(Icons.Rounded.AddCard,null);Text(" Kart")};FilledTonalButton(onClick={addInst=true},modifier=Modifier.weight(1f)){Icon(Icons.Rounded.Add,null);Text(" Taksit")}}};if(cards.isNotEmpty())item{Text("Kartlar",fontWeight=FontWeight.Bold,fontSize=18.sp)};items(cards,key={it.id}){c->AppCard{Text(c.name,fontWeight=FontWeight.Bold);Text(c.bank,color=Muted,fontSize=12.sp);KeyValue("Güncel ekstre",tl(c.statementBalance),modifier=Modifier.padding(top=8.dp));if(c.dueDate.isNotBlank())KeyValue("Son ödeme",dateLabel(c.dueDate),modifier=Modifier.padding(top=4.dp))}};item{Row(Modifier.fillMaxWidth()){Text("Aktif taksitler",fontWeight=FontWeight.Bold,fontSize=18.sp,modifier=Modifier.weight(1f));Text(tl(installments.filter{it.active}.sumOf{it.remainingDebt}),color=Red,fontWeight=FontWeight.Bold)}};if(installments.isEmpty())item{EmptyState("Taksit yok","Excel'den aktarabilir veya elle ekleyebilirsin.")};items(installments,key={it.id}){x->AppCard(onClick={edit=x}){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.merchant,fontWeight=FontWeight.SemiBold,maxLines=2,overflow=TextOverflow.Ellipsis);Text("${x.bank} • ${x.category}",color=Muted,fontSize=12.sp,modifier=Modifier.padding(top=3.dp));Text("${x.paidInstallments}/${x.totalInstallments} ödendi • ${x.nextMonth} → ${x.endMonth}",color=Muted,fontSize=11.sp,modifier=Modifier.padding(top=3.dp))};Column(horizontalAlignment=Alignment.End){Text(tl(x.monthlyAmount),fontWeight=FontWeight.Bold,color=Blue);Text("Kalan ${tl0(x.remainingDebt)}",fontSize=11.sp,color=Red)}}}}};if(addCard)CardDialog(vm){addCard=false};if(addInst)InstallmentDialog(null,vm){addInst=false};edit?.let{InstallmentDialog(it,vm){edit=null}}}

@Composable private fun CardDialog(vm:MainViewModel,onDismiss:()->Unit){var bank by remember{mutableStateOf("")};var name by remember{mutableStateOf("")};var last4 by remember{mutableStateOf("")};var balance by remember{mutableStateOf("")};var limit by remember{mutableStateOf("")};var due by remember{mutableStateOf("")};AlertDialog(onDismissRequest=onDismiss,title={Text("Kart ekle")},text={Column(verticalArrangement=Arrangement.spacedBy(7.dp)){FormField("Banka",bank,{bank=it});FormField("Kart adı",name,{name=it});FormField("Son 4 hane",last4,{last4=it},true);FormField("Güncel ekstre",balance,{balance=it},true);FormField("Kullanılabilir limit",limit,{limit=it},true);FormField("Son ödeme YYYY-MM-DD",due,{due=it})}},confirmButton={TextButton(onClick={vm.saveCard(vm.newCard(bank,name.ifBlank{bank},last4,doubleInput(balance),doubleInput(limit),due));onDismiss()}){Text("Kaydet")}},dismissButton={TextButton(onClick=onDismiss){Text("Vazgeç")}})}

@Composable private fun InstallmentDialog(item:InstallmentEntity?,vm:MainViewModel,onDismiss:()->Unit){var bank by remember{mutableStateOf(item?.bank.orEmpty())};var merchant by remember{mutableStateOf(item?.merchant.orEmpty())};var cat by remember{mutableStateOf(item?.category?:"Diğer")};var total by remember{mutableStateOf(item?.totalAmount?.toString()?:"")};var monthly by remember{mutableStateOf(item?.monthlyAmount?.toString()?:"")};var totalN by remember{mutableStateOf((item?.totalInstallments?:1).toString())};var paid by remember{mutableStateOf((item?.paidInstallments?:0).toString())};var next by remember{mutableStateOf(item?.nextMonth?:YearMonth.now().toString())};var end by remember{mutableStateOf(item?.endMonth?:YearMonth.now().toString())};AlertDialog(onDismissRequest=onDismiss,title={Text(if(item==null)"Taksit ekle" else "Taksiti düzenle")},text={LazyColumn(Modifier.heightIn(max=480.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){item{FormField("Banka/kart",bank,{bank=it})};item{FormField("İşlem/firma",merchant,{merchant=it})};item{FormField("Kategori",cat,{cat=it})};item{FormField("Toplam alışveriş",total,{total=it},true)};item{FormField("Aylık taksit",monthly,{monthly=it},true)};item{FormField("Toplam taksit",totalN,{totalN=it},true)};item{FormField("Ödenen",paid,{paid=it},true)};item{FormField("Sonraki ay YYYY-MM",next,{next=it})};item{FormField("Bitiş ayı YYYY-MM",end,{end=it})}}},confirmButton={TextButton(onClick={val p=paid.toIntOrNull()?:0;val x=if(item==null)vm.newInstallment(bank,merchant,cat,doubleInput(total),doubleInput(monthly),totalN.toIntOrNull()?:1,p,next,end)else item.copy(bank=bank,merchant=merchant,category=cat,totalAmount=doubleInput(total),monthlyAmount=doubleInput(monthly),totalInstallments=totalN.toIntOrNull()?:item.totalInstallments,paidInstallments=p,nextMonth=next,endMonth=end,remainingDebt=(doubleInput(total)-doubleInput(monthly)*p).coerceAtLeast(0.0));vm.saveInstallment(x);onDismiss()}){Text("Kaydet")}},dismissButton={Row{if(item!=null)TextButton(onClick={vm.deleteInstallment(item);onDismiss()}){Text("Sil",color=Red)};TextButton(onClick=onDismiss){Text("Vazgeç")}}})}

@Composable
fun AssetsScreen(vm:MainViewModel,assets:List<AssetEntity>){var add by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<AssetEntity?>(null)};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{SectionTitle("Varlıklar","Vadeli hesap, nakit, altın ve diğer birikimler"){FilledTonalButton(onClick={add=true}){Icon(Icons.Rounded.Add,null);Text(" Ekle")}}};item{MetricCard("Toplam varlık",tl(assets.sumOf{vm.repo.currentAssetValue(it)}),Teal)};if(assets.isEmpty())item{EmptyState("Varlık kaydı yok","Vadeli hesap veya başka bir varlık ekleyebilirsin.","Varlık ekle"){add=true}};items(assets,key={it.id}){a->AppCard(onClick={edit=a}){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(a.name,fontWeight=FontWeight.Bold);Text("${a.institution} • ${a.type}",color=Muted,fontSize=12.sp);if(a.type=="Vadeli Hesap")Text("%${a.annualRatePct} • ${a.maturityDate}",color=Green,fontSize=12.sp)};Text(tl(vm.repo.currentAssetValue(a)),fontWeight=FontWeight.Bold,color=Teal)}}}};if(add)AssetDialog(null,vm){add=false};edit?.let{AssetDialog(it,vm){edit=null}}}

@Composable private fun AssetDialog(item:AssetEntity?,vm:MainViewModel,onDismiss:()->Unit){var type by remember{mutableStateOf(item?.type?:"Vadeli Hesap")};var inst by remember{mutableStateOf(item?.institution.orEmpty())};var name by remember{mutableStateOf(item?.name.orEmpty())};var principal by remember{mutableStateOf(item?.principal?.toString()?:"")};var current by remember{mutableStateOf(item?.currentValue?.toString()?:"")};var rate by remember{mutableStateOf(item?.annualRatePct?.toString()?:"")};var tax by remember{mutableStateOf(item?.withholdingPct?.toString()?:"")};var start by remember{mutableStateOf(item?.startDate?:LocalDate.now().toString())};var end by remember{mutableStateOf(item?.maturityDate?:LocalDate.now().plusMonths(1).toString())};var note by remember{mutableStateOf(item?.note.orEmpty())};AlertDialog(onDismissRequest=onDismiss,title={Text(if(item==null)"Varlık ekle" else "Varlığı düzenle")},text={LazyColumn(Modifier.heightIn(max=500.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){item{FormField("Tür: Vadeli Hesap/Nakit/Altın/Diğer",type,{type=it})};item{FormField("Banka / kurum",inst,{inst=it})};item{FormField("Ad",name,{name=it})};item{FormField("Ana para",principal,{principal=it},true)};item{FormField("Güncel değer",current,{current=it},true)};if(type.contains("Vadeli",true)){item{FormField("Yıllık faiz %",rate,{rate=it},true)};item{FormField("Stopaj %",tax,{tax=it},true)};item{FormField("Başlangıç YYYY-MM-DD",start,{start=it})};item{FormField("Vade sonu YYYY-MM-DD",end,{end=it})}};item{FormField("Not",note,{note=it},false,false)}}},confirmButton={TextButton(onClick={val c=doubleInput(current).takeIf{it>0}?:doubleInput(principal);val x=if(item==null)vm.newAsset(type,inst,name,doubleInput(principal),c,doubleInput(rate),doubleInput(tax),start,end,note)else item.copy(type=type,institution=inst,name=name,principal=doubleInput(principal),currentValue=c,annualRatePct=doubleInput(rate),withholdingPct=doubleInput(tax),startDate=start,maturityDate=end,note=note);vm.saveAsset(x);onDismiss()}){Text("Kaydet")}},dismissButton={Row{if(item!=null)TextButton(onClick={vm.deleteAsset(item);onDismiss()}){Text("Sil",color=Red)};TextButton(onClick=onDismiss){Text("Vazgeç")}}})}
