package com.mercan.fuzulbutce;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.*;

public class MainActivity extends Activity {
  static final int IMP=7001, EXP=7002; static final String PREF="fuzul_budget", KEY="plan";
  static final int BG=Color.rgb(245,247,250), NAVY=Color.rgb(24,63,95), TEAL=Color.rgb(15,118,110), BLUE=Color.rgb(37,99,235), GREEN=Color.rgb(22,101,52), RED=Color.rgb(185,28,28), TEXT=Color.rgb(31,41,55), MUTED=Color.rgb(107,114,128), BORDER=Color.rgb(226,232,240);
  SharedPreferences prefs; JSONObject data; LinearLayout host, nav; int tab=0;

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);prefs=getSharedPreferences(PREF,MODE_PRIVATE);load();shell();show(0);}  
  void load(){try{String s=prefs.getString(KEY,null);data=s==null?null:new JSONObject(s);}catch(Exception e){data=null;}}
  void save(){if(data!=null)prefs.edit().putString(KEY,data.toString()).apply();}

  void shell(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(BG);
    LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(dp(18),dp(14),dp(18),dp(12));top.setBackgroundColor(NAVY);top.addView(t("Fuzul Bütçe",22,Color.WHITE,true));top.addView(t("Hane nakit akışı • sözleşme • araç farkı",12,Color.LTGRAY,false));r.addView(top);
    host=new LinearLayout(this);host.setOrientation(LinearLayout.VERTICAL);r.addView(host,new LinearLayout.LayoutParams(-1,0,1));
    HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setPadding(dp(6),dp(5),dp(6),dp(7));hs.addView(nav);String[] names={"Özet","Aylık Plan","Fuzul","Araç","Veri"};for(int i=0;i<names.length;i++){final int x=i;Button q=btn(names[i],false);q.setOnClickListener(v->show(x));nav.addView(q,new LinearLayout.LayoutParams(dp(100),dp(46)));}r.addView(hs);setContentView(r);}

  void show(int x){tab=x;host.removeAllViews();if(data==null&&x!=4){noData();return;}if(x==0)dashboard();else if(x==1)months();else if(x==2)fuzul();else if(x==3)vehicle();else files();}
  LinearLayout page(){ScrollView s=new ScrollView(this);host.addView(s,new LinearLayout.LayoutParams(-1,-1));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(14),dp(14),dp(28));s.addView(c);return c;}
  void noData(){LinearLayout c=page();c.addView(t("Plan verisini yükleyelim",24,TEXT,true));c.addView(t("Excel'den hazırlanan JSON dosyasını seç. Veriler yalnızca telefonda tutulur.",14,MUTED,false),mt(8));Button b=btn("JSON planını seç",true);b.setOnClickListener(v->importJson());c.addView(b,mt(18));}

  void dashboard(){LinearLayout c=page();JSONObject ct=data.optJSONObject("contract");JSONArray ms=data.optJSONArray("months");c.addView(t("Bugünkü durum",22,TEXT,true));Payment p=next(ms);LinearLayout a=card();a.addView(t(p.overdue?"GECİKMİŞ ÖDEME":"SONRAKİ FUZUL ÖDEMESİ",12,p.overdue?RED:TEAL,true));a.addView(t(p.title,21,TEXT,true),mt(6));a.addView(t(tl(p.amount),30,TEXT,true),mt(6));a.addView(t(p.sub,13,MUTED,false),mt(4));c.addView(a,mt(14));
    int ai=indexFor(ms,ct.optString("allocationDate"));double paid=ct.optDouble("downPayment")+cumF(ms,ai);double cash=cumCash(ms,ai,ct.optDouble("openingCash"));LinearLayout b=card();b.addView(t("TAHSİSAT",12,BLUE,true));b.addView(t(date(ct.optString("allocationDate")),21,TEXT,true),mt(5));b.addView(kv("Peşinat + tahsisata kadar taksit",tl(paid)),mt(8));b.addView(kv("Birikim oranı",pct(paid/ct.optDouble("amount"))),mt(5));b.addView(kv("Tahsisat ayı serbest nakit",tl(cash)),mt(5));c.addView(b,mt(10));
    LinearLayout d=card();d.addView(t("24 AYLIK NAKİT",12,TEAL,true));d.addView(kv("Başlangıç devri",tl(ct.optDouble("openingCash"))),mt(8));d.addView(kv("24 ay sonu",tl(cumCash(ms,ms.length()-1,ct.optDouble("openingCash")))),mt(5));d.addView(kv("En kötü ay",tl(worst(ms))),mt(5));c.addView(d,mt(10));}

  void months(){LinearLayout c=page();c.addView(t("24 aylık plan",22,TEXT,true));c.addView(t("Aya dokun: maaş, gider ve Fuzul tutarını düzenle.",13,MUTED,false),mt(4));JSONArray ms=data.optJSONArray("months");double run=data.optJSONObject("contract").optDouble("openingCash");for(int i=0;i<ms.length();i++){JSONObject m=ms.optJSONObject(i);double inc=income(m),exp=expense(m),f=m.optDouble("fuzul"),net=inc-exp-f;run+=net;LinearLayout q=card();q.addView(t(month(m.optString("month")),16,TEXT,true));q.addView(t("Gelir "+tl0(inc)+"   Gider "+tl0(exp)+"   Fuzul "+tl0(f),12,MUTED,false),mt(6));q.addView(t("Bu ay: "+tl(net)+"   Birikmiş: "+tl(run),13,net<0?RED:GREEN,true),mt(6));final int z=i;q.setOnClickListener(v->edit(z));c.addView(q,mt(8));}}

  void edit(int idx){JSONArray ms=data.optJSONArray("months");JSONObject m=ms.optJSONObject(idx);String[] keys={"mete","esma","otherIncome","orgFee","bills","living","cards","education","transport","otherExpense","fuzul"};String[] labels={"Mete maaş/nakit","Esma net maaş","Diğer gelir","Org. ücreti","Faturalar","Market + giyim + yeme","Kredi/kart","Çocuk/eğitim","Ulaşım/yakıt","Diğer/kişisel","Fuzul taksiti"};LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);EditText[] es=new EditText[keys.length];for(int i=0;i<keys.length;i++){form.addView(t(labels[i],12,MUTED,true),mt(i==0?2:8));EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setText(String.valueOf(m.optDouble(keys[i])));e.setSelectAllOnFocus(true);form.addView(e);es[i]=e;}ScrollView sv=new ScrollView(this);sv.setPadding(dp(14),0,dp(14),0);sv.addView(form);new AlertDialog.Builder(this).setTitle(month(m.optString("month"))).setView(sv).setNegativeButton("Vazgeç",null).setPositiveButton("Kaydet",(d,w)->{try{for(int i=0;i<keys.length;i++)m.put(keys[i],num(es[i].getText().toString()));save();show(1);}catch(Exception e){toast("Kaydetme hatası");}}).show();}

  void fuzul(){LinearLayout c=page();JSONObject ct=data.optJSONObject("contract");JSONArray ms=data.optJSONArray("months");c.addView(t("Fuzul sözleşmesi",22,TEXT,true));LinearLayout a=card();a.addView(kv("Finansman türü",ct.optString("fundingType")));a.addView(kv("Sözleşme tutarı",tl(ct.optDouble("amount"))),mt(5));a.addView(kv("Peşinat",tl(ct.optDouble("downPayment"))),mt(5));a.addView(kv("Organizasyon ücreti",tl(ct.optDouble("organizationFee"))),mt(5));a.addView(kv("Tahsisat",date(ct.optString("allocationDate"))),mt(5));c.addView(a,mt(12));if("Konut".equalsIgnoreCase(ct.optString("fundingType"))){LinearLayout w=card();w.addView(t("Sözleşmede finansman türü “Konut” görünüyor",14,RED,true));w.addView(t("Araç kullanımı için yazılı teyit almak iyi olur.",13,MUTED,false),mt(4));c.addView(w,mt(10));}c.addView(t("Ödeme takvimi",18,TEXT,true),mt(18));for(int i=0;i<ms.length();i++){JSONObject m=ms.optJSONObject(i);if(m.optDouble("fuzul")<=0)continue;LinearLayout q=card();LinearLayout line=new LinearLayout(this);line.setOrientation(LinearLayout.HORIZONTAL);line.addView(t("05 "+month(m.optString("month")),14,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));CheckBox cb=new CheckBox(this);cb.setText("Ödendi");cb.setChecked(m.optBoolean("paid"));final int z=i;cb.setOnCheckedChangeListener((v,on)->{try{ms.optJSONObject(z).put("paid",on);save();}catch(Exception ignored){}});line.addView(cb);q.addView(line);double f=m.optDouble("fuzul"),o=m.optDouble("orgFee");q.addView(t("Taksit "+tl(f)+(o>0?" + Org. "+tl(o):""),13,MUTED,false),mt(4));q.addView(t("Toplam: "+tl(f+o),15,BLUE,true),mt(4));c.addView(q,mt(8));}}

  void vehicle(){LinearLayout c=page();JSONObject ct=data.optJSONObject("contract");JSONArray ms=data.optJSONArray("months");c.addView(t("Araç farkı hesapla",22,TEXT,true));LinearLayout a=card();a.addView(t("Araç satış fiyatı",13,MUTED,true));EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setText("2800000");e.setTextSize(22);a.addView(e);TextView out=t("",14,TEXT,true);Button b=btn("Hesapla",true);b.setOnClickListener(v->{double price=num(e.getText().toString()),finance=ct.optDouble("amount"),diff=Math.max(price-finance,0),cash=cumCash(ms,indexFor(ms,ct.optString("allocationDate")),ct.optDouble("openingCash")),shortage=Math.max(diff-cash,0);out.setText("Fuzul: "+tl(finance)+"\nSizin fark: "+tl(diff)+"\nTahsisat ayı nakit: "+tl(cash)+"\n\n"+(shortage<=0?"✓ Karşılanıyor. Kalan: "+tl(cash-diff):"⚠ Ek nakit ihtiyacı: "+tl(shortage)));out.setTextColor(shortage>0?RED:GREEN);});a.addView(b,mt(8));a.addView(out,mt(12));c.addView(a,mt(12));}

  void files(){LinearLayout c=page();c.addView(t("Veri yönetimi",22,TEXT,true));c.addView(t("Plan cihazda saklanır; uygulamanın internet izni yoktur.",13,MUTED,false),mt(4));Button a=btn("JSON içe aktar",true);a.setOnClickListener(v->importJson());c.addView(a,mt(14));Button b=btn("Yedeği dışa aktar",false);b.setEnabled(data!=null);b.setOnClickListener(v->exportJson());c.addView(b,mt(8));Button d=btn("Cihazdaki veriyi sıfırla",false);d.setTextColor(RED);d.setEnabled(data!=null);d.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Veriyi sıfırla").setMessage("Plan silinsin mi?").setNegativeButton("Vazgeç",null).setPositiveButton("Sil",(x,y)->{data=null;prefs.edit().clear().apply();show(4);}).show());c.addView(d,mt(8));}

  void importJson(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/json","text/plain","application/octet-stream"});startActivityForResult(i,IMP);}void exportJson(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"FuzulButce_Yedek.json");startActivityForResult(i,EXP);}
  @Override protected void onActivityResult(int req,int result,Intent it){super.onActivityResult(req,result,it);if(result!=RESULT_OK||it==null||it.getData()==null)return;Uri u=it.getData();try{if(req==IMP){String raw=read(getContentResolver().openInputStream(u));JSONObject x=new JSONObject(raw);if(!x.has("contract")||!x.has("months"))throw new Exception();data=x;save();toast("Plan yüklendi");show(0);}else if(req==EXP&&data!=null){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(data.toString(2).getBytes(StandardCharsets.UTF_8));}toast("Yedek kaydedildi");}}catch(Exception e){toast("Dosya işlemi başarısız");}}

  Payment next(JSONArray ms){LocalDate now=LocalDate.now();Payment future=null;for(int i=0;i<ms.length();i++){JSONObject m=ms.optJSONObject(i);if(m.optDouble("fuzul")<=0||m.optBoolean("paid"))continue;LocalDate due;try{due=YearMonth.parse(m.optString("month")).atDay(5);}catch(Exception e){continue;}double amount=m.optDouble("fuzul")+m.optDouble("orgFee");long days=ChronoUnit.DAYS.between(now,due);if(days<0)return new Payment(month(m.optString("month"))+" • 5'i",amount,Math.abs(days)+" gün gecikmiş",true);if(future==null)future=new Payment(month(m.optString("month"))+" • 5'i",amount,days==0?"Bugün son gün":days+" gün kaldı",false);}return future==null?new Payment("Aktif ödeme yok",0,"Plan tamamlanmış veya tüm ödemeler işaretli",false):future;}
  double income(JSONObject m){return m.optDouble("mete")+m.optDouble("esma")+m.optDouble("otherIncome");}double expense(JSONObject m){return m.optDouble("orgFee")+m.optDouble("bills")+m.optDouble("living")+m.optDouble("cards")+m.optDouble("education")+m.optDouble("transport")+m.optDouble("otherExpense");}
  double cumCash(JSONArray ms,int end,double opening){double x=opening;for(int i=0;i<ms.length()&&i<=end;i++){JSONObject m=ms.optJSONObject(i);x+=income(m)-expense(m)-m.optDouble("fuzul");}return x;}double cumF(JSONArray ms,int end){double x=0;for(int i=0;i<ms.length()&&i<=end;i++)x+=ms.optJSONObject(i).optDouble("fuzul");return x;}double worst(JSONArray ms){double x=Double.MAX_VALUE;for(int i=0;i<ms.length();i++){JSONObject m=ms.optJSONObject(i);x=Math.min(x,income(m)-expense(m)-m.optDouble("fuzul"));}return x==Double.MAX_VALUE?0:x;}int indexFor(JSONArray ms,String date){String ym=date!=null&&date.length()>=7?date.substring(0,7):"";for(int i=0;i<ms.length();i++)if(ym.equals(ms.optJSONObject(i).optString("month")))return i;return 0;}

  LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(15),dp(14),dp(15),dp(14));l.setBackground(rr(Color.WHITE,16,BORDER));l.setElevation(dp(1));return l;}GradientDrawable rr(int fill,int rad,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(rad));g.setStroke(dp(1),stroke);return g;}TextView t(String s,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}TextView kv(String k,String v){return t(k+"\n"+v,13,TEXT,false);}Button btn(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(primary?Color.WHITE:BLUE);b.setBackground(rr(primary?TEAL:Color.WHITE,12,primary?TEAL:BORDER));return b;}LinearLayout.LayoutParams mt(int n){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(n);return p;}int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
  double num(String s){try{String x=s.trim().replace(" TL","").replace("₺","").replace(" ","");if(x.contains(",")&&x.contains("."))x=x.replace(".","").replace(',','.');else if(x.contains(","))x=x.replace(',','.');return Double.parseDouble(x);}catch(Exception e){return 0;}}
  String tl(double v){DecimalFormatSymbols s=new DecimalFormatSymbols(new Locale("tr","TR"));s.setGroupingSeparator('.');s.setDecimalSeparator(',');return new DecimalFormat("#,##0.00 'TL'",s).format(v);}String tl0(double v){DecimalFormatSymbols s=new DecimalFormatSymbols(new Locale("tr","TR"));s.setGroupingSeparator('.');return new DecimalFormat("#,##0 'TL'",s).format(v);}String pct(double v){return new DecimalFormat("0.0%").format(v);}String month(String ym){try{return YearMonth.parse(ym).format(DateTimeFormatter.ofPattern("MMMM yyyy",new Locale("tr","TR")));}catch(Exception e){return ym;}}String date(String iso){try{return LocalDate.parse(iso).format(DateTimeFormatter.ofPattern("d MMMM yyyy",new Locale("tr","TR")));}catch(Exception e){return iso;}}
  String read(InputStream in)throws Exception{BufferedReader b=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l).append('\n');b.close();return s.toString();}
  static class Payment{String title,sub;double amount;boolean overdue;Payment(String t,double a,String s,boolean o){title=t;amount=a;sub=s;overdue=o;}}
}
